import { createSlice, current, PayloadAction } from "@reduxjs/toolkit";
import { DIVISOR } from "../../constants/MinimumCoin";
import { RootState } from "../core/store";

export interface Coin {
  amount: number;
  symbol: string;
  visible: boolean;
}
export interface Coins {
  [index: string]: Coin;
}

export interface Nimonics extends Array<string> {}

export interface User {
  privateKey: string;
  walletAddress: string;
  nimonics: Nimonics;
  coins: Coins;
  visible: boolean;
}

interface Users extends Array<User> {}

interface CoinBase {
  name: string;
  symbol: string;
}

interface InitialWallets {
  users: Users;
  currentWallet: string;
  allCoins: { [index: string]: CoinBase };
}

const initialWallets: InitialWallets = {
  currentWallet: "",
  users: [],
  allCoins: {},
};

export interface CreateToken {
  address: string;
  name: string;
  symbol: string;
  amount: number;
}

export const walletSlice = createSlice({
  name: "wallet",
  initialState: initialWallets,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    createUser: (state, action: PayloadAction<User>) => {
      const newUsersArray: Users = [...state.users, action.payload];
      // eslint-disable-next-line @typescript-eslint/no-unused-expressions
      (state.users = newUsersArray),
        (state.currentWallet = action.payload.walletAddress);
      console.log(state.users[0]);
    },
    onCreateToken: (state, action: PayloadAction<CreateToken>) => {
      if (state.currentWallet === "") {
        alert("please login first");
        return;
      }
      const currentUserIndex = state.users.findIndex(
        (user) => user.walletAddress === state.currentWallet
      );
      const currentUserData: User = JSON.parse(
        JSON.stringify(current(state.users[currentUserIndex]))
      );
      currentUserData.coins[action.payload.address] = {
        amount: action.payload.amount / DIVISOR,
        symbol: action.payload.symbol,
        visible: true,
      };

      // eslint-disable-next-line @typescript-eslint/no-unused-expressions
      (state.users[currentUserIndex] = currentUserData),
        (state.allCoins[action.payload.address] = {
          name: action.payload.name,
          symbol: action.payload.symbol,
        });
    },
    onChangeCurrentUser: (state, action: PayloadAction<string>) => {
      state.currentWallet = action.payload;
    },
    onChangeUserCoinVisible: (state, action: PayloadAction<string>) => {
      const currentUserIndex = state.users.findIndex(
        (user) => user.walletAddress === state.currentWallet
      );
      const currentUserData: User = JSON.parse(
        JSON.stringify(current(state.users[currentUserIndex]))
      );
      const newUserCoin: Coin = currentUserData.coins[action.payload]
        ? {
            visible: true,
            amount: currentUserData.coins[action.payload].amount,
            symbol: state.allCoins[action.payload].symbol,
          }
        : {
            visible: true,
            amount: 0,
            symbol: state.allCoins[action.payload].symbol,
          };
      console.log(newUserCoin);
      state.users[currentUserIndex].coins[action.payload] = newUserCoin;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
});

export const {
  createUser,
  onCreateToken,
  onChangeCurrentUser,
  onChangeUserCoinVisible,
} = walletSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectUsers = (state: RootState) => state.wallet.users;
export const selectCurrentWallet = (state: RootState) =>
  state.wallet.currentWallet;
export const selectCurrentUserData = (state: RootState) => {
  if (state.wallet.currentWallet === "") {
    return {
      privateKey: "",
      walletAddress: "",
      nimonics: [],
      coins: {},
      visible: false,
    };
  }
  const temp = [...state.wallet.users];
  const currentUserIndex = temp.findIndex(
    (user) => state.wallet.currentWallet === user.walletAddress
  );

  return temp[currentUserIndex];
};
export const selectAllCoins = (state: RootState) => state.wallet.allCoins;
export default walletSlice.reducer;
